name: Bump Version and Auto-Merge

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read current version
        id: read_version
        run: |
          current_version=$(cat VERSION)
          echo "Current version: $current_version"
          IFS='.' read -r -a parts <<< "$current_version"
          major=${parts[0]}
          minor=${parts[1]}
          patch=${parts[2]}
          patch=$((patch+1))
          new_version="$major.$minor.$patch"
          echo "New version: $new_version"
          echo "::set-output name=new_version::$new_version"

      - name: Update version file
        run: echo "${{ steps.read_version.outputs.new_version }}" > VERSION

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add VERSION
          git commit -m "Bump version to ${{ steps.read_version.outputs.new_version }}"

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "Bump version to ${{ steps.read_version.outputs.new_version }}"
          branch: "version-bump-${{ steps.read_version.outputs.new_version }}"
          title: "Bump version to ${{ steps.read_version.outputs.new_version }}"
          body: "Automatically created pull request to update version."
          base: main
          auto-merge: true

      - name: Enable Auto-Merge
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          pull-request-number: ${{ steps.create_pr.outputs.pull-request-number }}
          merge-method: squash
