name: Bump Version and Auto-Merge

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Convert line endings to LF for gradlew
        run: sed -i 's/\r$//' ./gradlew

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

  bump-version:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Bump Version
        run: |
          current_version=$(cat VERSION)
          new_version=$(echo "$current_version" | awk -F. -v OFS=. '{$NF++; print}')
          echo "$new_version" > VERSION
          git add VERSION
          git commit -m "Bump version to $new_version"

      - name: Push Changes
        env:
          TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/Volodymyr-Petrunin/Planning-Poker.git
          git push origin main

  enable-auto-merge:
    runs-on: ubuntu-latest
    needs: bump-version
    steps:
      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
