name: Update Version on Merge to Main

on:
  push:
    branches:
      - main

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "${{ secrets.OWNER_EMAIL }}"    

      - name: Read current version
        id: read_version
        run: |
          current_version=$(cat VERSION)
          echo "Current version: $current_version"
          IFS='.' read -r -a parts <<< "$current_version"
          major=${parts[0]}
          minor=${parts[1]}
          patch=${parts[2]}
          patch=$((patch+1))
          new_version="$major.$minor.$patch"
          echo "New version: $new_version"
          echo "::set-output name=new_version::$new_version"

      - name: Update version file
        run: echo "${{ steps.read_version.outputs.new_version }}" > VERSION

      - name: Commit changes
        run: |
          git add VERSION
          git commit -m "Bump version to ${{ steps.read_version.outputs.new_version }}" || echo "No changes to commit"

      - name: Push new version to dev
        run: |
          git push origin dev
          git push origin --tags
