name: Update Version on Merge to Main

on:
  push:
    branches:
      - main

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read current version
        id: read_version
        run: |
          current_version=$(cat VERSION)
          echo "Current version: $current_version"
          IFS='.' read -r -a parts <<< "$current_version"
          major=${parts[0]}
          minor=${parts[1]}
          patch=${parts[2]}
          patch=$((patch+1))
          new_version="$major.$minor.$patch"
          echo "New version: $new_version"
          echo "::set-output name=new_version::$new_version"

      - name: Update version file
        run: echo "${{ steps.read_version.outputs.new_version }}" > VERSION

      - name: Create a new branch for the version update
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          branch_name="version-bump-${{ steps.read_version.outputs.new_version }}"
          git checkout -b $branch_name
          git add VERSION
          git commit -m "Bump version to ${{ steps.read_version.outputs.new_version }}"
          git push origin $branch_name

      - name: Create Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            const { data: pullRequest } = await github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Bump version to ${{ steps.read_version.outputs.new_version }}`,
              head: `${branch_name}`,
              base: 'main',
              body: 'Automatically created pull request to update version.',
              draft: false
            });
            console.log(`Pull Request created: ${pullRequest.html_url}`);
